
import java.util.stream.IntStream;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RamyaRanjan
 */
public class function_point extends javax.swing.JFrame {

    /**
     * Creates new form function_pointer
     */
    
    final static int COMPLEXITY_VALUE_MAT[][]= {{3,4,6},{4,5,7},{3,4,6},{7,10,15},{5,7,10}};
    
    public function_point() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        user_inputs = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputs = new javax.swing.JTextPane();
        user_outputs = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        outputs = new javax.swing.JTextPane();
        user_inquiries = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        inquiries = new javax.swing.JTextPane();
        user_files = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        files = new javax.swing.JTextPane();
        ext_interfaces = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        interfaces = new javax.swing.JTextPane();
        option_inputs = new javax.swing.JComboBox<>();
        option_outputs = new javax.swing.JComboBox<>();
        option_inquiries = new javax.swing.JComboBox<>();
        option_files = new javax.swing.JComboBox<>();
        option_interfaces = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        complex_adjust_value = new javax.swing.JTextArea();
        result_CAF = new javax.swing.JTextField();
        result_FP = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();
        result_UFP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText(" Funtion Point calculation");

        user_inputs.setBackground(new java.awt.Color(255, 255, 0));
        user_inputs.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        user_inputs.setText("    Number of inputs:");
        user_inputs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_inputsActionPerformed(evt);
            }
        });

        inputs.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane2.setViewportView(inputs);

        user_outputs.setBackground(new java.awt.Color(255, 255, 0));
        user_outputs.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        user_outputs.setText("    Number of outputs:");
        user_outputs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_outputsActionPerformed(evt);
            }
        });

        outputs.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane3.setViewportView(outputs);

        user_inquiries.setBackground(new java.awt.Color(255, 255, 0));
        user_inquiries.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        user_inquiries.setText("    Number of inquiries:");

        inquiries.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane4.setViewportView(inquiries);

        user_files.setBackground(new java.awt.Color(255, 255, 0));
        user_files.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        user_files.setText("    Number of files:");

        files.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane5.setViewportView(files);

        ext_interfaces.setBackground(new java.awt.Color(255, 255, 0));
        ext_interfaces.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        ext_interfaces.setText("Number ofexternal interfaces:");

        interfaces.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane6.setViewportView(interfaces);

        option_inputs.setBackground(new java.awt.Color(0, 102, 102));
        option_inputs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Average", "Complex" }));
        option_inputs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option_inputsActionPerformed(evt);
            }
        });

        option_outputs.setBackground(new java.awt.Color(0, 102, 102));
        option_outputs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Average", "Complex" }));

        option_inquiries.setBackground(new java.awt.Color(0, 102, 102));
        option_inquiries.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Average", "Complex" }));

        option_files.setBackground(new java.awt.Color(0, 102, 102));
        option_files.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Average", "Complex" }));

        option_interfaces.setBackground(new java.awt.Color(0, 102, 102));
        option_interfaces.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Average", "Complex" }));

        jTextField6.setBackground(new java.awt.Color(153, 255, 204));
        jTextField6.setText("Complexity adjustment values with space separated :");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        complex_adjust_value.setColumns(20);
        complex_adjust_value.setRows(5);
        jScrollPane7.setViewportView(complex_adjust_value);

        result_CAF.setBackground(new java.awt.Color(204, 255, 204));
        result_CAF.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        result_CAF.setText("CAF :");
        result_CAF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result_CAFActionPerformed(evt);
            }
        });

        result_FP.setBackground(new java.awt.Color(204, 255, 204));
        result_FP.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        result_FP.setText("FP:");
        result_FP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result_FPActionPerformed(evt);
            }
        });

        calculate.setBackground(new java.awt.Color(204, 204, 255));
        calculate.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        calculate.setForeground(new java.awt.Color(255, 0, 0));
        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        result_UFP.setBackground(new java.awt.Color(204, 255, 204));
        result_UFP.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        result_UFP.setText("UFP :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Enter values here");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Simple/Avg/Complex");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user_inquiries, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(user_files, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ext_interfaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user_inputs)
                            .addComponent(user_outputs))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane6)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(option_inputs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(option_outputs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(option_inquiries, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(option_files, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(option_interfaces, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calculate)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(result_UFP, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(result_CAF, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(result_FP, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(option_inputs, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(option_outputs, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(user_inputs, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user_outputs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(option_inquiries)
                    .addComponent(user_inquiries)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(option_files)
                    .addComponent(user_files)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(option_interfaces)
                    .addComponent(ext_interfaces)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(result_UFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(result_CAF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(result_FP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(calculate)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_inputsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_inputsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_inputsActionPerformed

    private void user_outputsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_outputsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_outputsActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        int Noi=Integer.parseInt(inputs.getText());
        int Noo=Integer.parseInt(outputs.getText());
        int Noinq=Integer.parseInt(inquiries.getText());
        int Nof=Integer.parseInt(files.getText());
        int Noextinf=Integer.parseInt(interfaces.getText());
        //System.out.println(""+no_of_inputs+no_of_outputs+no_of_Inquiries+no_of_files+no_of_externalinterfaces);
        int inplev=getcomplev(String.valueOf(option_inputs.getSelectedItem()));
        int outlev=getcomplev(String.valueOf(option_outputs.getSelectedItem()));
        int Inqlev=getcomplev(String.valueOf(option_inquiries.getSelectedItem()));
        int filelev=getcomplev(String.valueOf(option_files.getSelectedItem()));
        int extinflev=getcomplev(String.valueOf(option_interfaces.getSelectedItem()));
        //System.out.println(""+inputlevel+outputlevel+Inquirylevel+filelevel+externalinterfacelevel);
        
        int udp=calcUFP(Noi,Noo,Nof,Noinq,Noextinf,
                inplev,outlev,filelev,Inqlev,extinflev);
        int di=calcDI();
        
        float caf=0.65f + 0.01f*di;
        float FP_val=(float)udp*caf;
        float newfp=(float)FP_val;
        result_UFP.setText("UPF = "+Integer.toString(udp));
        result_CAF.setText("CAF = "+Float.toString(caf));
        result_FP.setText("FP = "+Float.toString(newfp));
    }//GEN-LAST:event_calculateActionPerformed

    private void result_FPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result_FPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_result_FPActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void option_inputsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option_inputsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option_inputsActionPerformed

    private void result_CAFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result_CAFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_result_CAFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(function_point.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(function_point.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(function_point.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(function_point.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new function_point().setVisible(true);
            }
        });
    }
    
    private int getcomplev(String valueOf) {
        
        if(valueOf.equalsIgnoreCase("Simple")) return 0;
        else if(valueOf.equalsIgnoreCase("Average")) return 1;
        else return 2;
    }

    private int calcUFP(int no_of_inputs, int no_of_outputs, int no_of_files, int no_of_Inquiries, int no_of_externalinterfaces,
            int inputlevel, int outputlevel, int filelevel, int Inquirylevel, int externalinterfacelevel) {
        
        int UFP=no_of_inputs*COMPLEXITY_VALUE_MAT[0][inputlevel]+
                no_of_outputs*COMPLEXITY_VALUE_MAT[1][outputlevel]+
                no_of_Inquiries*COMPLEXITY_VALUE_MAT[2][Inquirylevel]+
                no_of_files*COMPLEXITY_VALUE_MAT[3][filelevel]+
                no_of_externalinterfaces*COMPLEXITY_VALUE_MAT[4][externalinterfacelevel] ;
        return UFP;
    }

    private int calcDI() {

        String CAV_field=complex_adjust_value.getText();
        String Adjustment_StringValues[]=CAV_field.split(" ");
        int Adjustment_Values[]= new int[14];
        for(int i=0;i<Adjustment_StringValues.length;i++){
          Adjustment_Values[i]=Integer.parseInt(Adjustment_StringValues[i].trim());
        }
        System.out.println("Tota DI: " + IntStream.of(Adjustment_Values).sum());
        return IntStream.of(Adjustment_Values).sum();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate;
    private javax.swing.JTextArea complex_adjust_value;
    private javax.swing.JTextField ext_interfaces;
    private javax.swing.JTextPane files;
    private javax.swing.JTextPane inputs;
    private javax.swing.JTextPane inquiries;
    private javax.swing.JTextPane interfaces;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JComboBox<String> option_files;
    private javax.swing.JComboBox<String> option_inputs;
    private javax.swing.JComboBox<String> option_inquiries;
    private javax.swing.JComboBox<String> option_interfaces;
    private javax.swing.JComboBox<String> option_outputs;
    private javax.swing.JTextPane outputs;
    private javax.swing.JTextField result_CAF;
    private javax.swing.JTextField result_FP;
    private javax.swing.JTextField result_UFP;
    private javax.swing.JTextField user_files;
    private javax.swing.JTextField user_inputs;
    private javax.swing.JTextField user_inquiries;
    private javax.swing.JTextField user_outputs;
    // End of variables declaration//GEN-END:variables
}
